version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gato_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: E6NzIp5y3cY76PWHmITgWgxPBH5bi6MK3thDHvOfbttfnJYUdr  # <--- MUDANÃ‡A AQUI (Senha simples)
      POSTGRES_DB: gatocomics_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: gato_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: